spring:
  application:
    name: canvas-course-finder
  profiles:
    active: redis
  session:
    store-type: none
#  output:
#    ansi:
#      enabled: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
canvas-course-finder:
  version: @app.version@
  env: ${app.env}

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

---

spring:
  profiles: redis
  session:
    store-type: redis
    redis.namespace: canvas-course-finder-${app.version}:session